- name: Create cocubo directory structure
  become: true
  file:
    path: "/opt/cocubo"
    state: directory

- name: Copy cocubo spring jar
  become: yes
  copy:
    src: "../../../target/cocubo-1.jar"
    dest: "/opt/cocubo/cocubo.jar"
#
#- name: Start spring boot application
#  become: yes
#  shell: 'nohup java -jar /opt/cocubo/cocubo.jar'
#  async: 45
#  poll: 0